<?php

namespace App\Http\Controllers;

use App\Models\Peminjaman;
use App\Models\Ruangan;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class PeminjamanController extends Controller
{
    public function create()
    {
        $ruangans = Ruangan::where('is_tersedia', true)->get();
        return view('peminjaman.create', compact('ruangans'));
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'nama_kegiatan'     => 'required|string|max:100',
            'latar_belakang'    => 'nullable|string|max:100',
            'tujuan_kegiatan'   => 'nullable|string|max:100',
            'sasaran_peserta'   => 'nullable|string|max:100',
            'jumlah_peserta'    => 'nullable|integer|min:1',
            'narasumber'        => 'nullable|string|max:100',
            'pj_kegiatan'       => 'required|string|max:100',
            'instansi'          => 'nullable|string|max:100',
            'alamat_instansi'   => 'nullable|string|max:100',
            'wilayah'           => 'nullable|string|max:100',
            'no_hp_pj'          => 'required|string',
            'fasilitas_tambahan'=> 'nullable|array',
            'ruangan_id'        => 'required|string|exists:ruangans,id_ruangan',
            'tgl_penggunaan'    => 'required|date',
            'jam_mulai'         => 'required',
            'jam_berakhir'      => 'required',
            'berkas_ktp'        => 'nullable|file|mimes:jpg,jpeg,png,pdf|max:10240',
            'berkas_surat'      => 'nullable|file|mimes:jpg,jpeg,png,pdf|max:10240',
            'berkas_poster'     => 'nullable|file|mimes:jpg,jpeg,png,pdf|max:10240',
        ]);

        // Normalize fasilitas into string for long description
        $facilitiesText = null;
        if (!empty($validated['fasilitas_tambahan'])) {
            $facilitiesText = is_array($validated['fasilitas_tambahan']) ? implode(', ', $validated['fasilitas_tambahan']) : (string) $validated['fasilitas_tambahan'];
        }

        // Handle file uploads
        $gambarPath = null;
        $ktpPath = null;
        $suratPath = null;
        if ($request->hasFile('berkas_poster')) {
            $gambarPath = $request->file('berkas_poster')->store('peminjaman', 'public');
        }
        if ($request->hasFile('berkas_ktp')) {
            $ktpPath = $request->file('berkas_ktp')->store('peminjaman', 'public');
        }
        if ($request->hasFile('berkas_surat')) {
            $suratPath = $request->file('berkas_surat')->store('peminjaman', 'public');
        }

        Peminjaman::create([
            // ID will be auto-generated by Model's boot method
            'ruangan_id'        => $validated['ruangan_id'],
            'nama_kegiatan'     => $validated['nama_kegiatan'],
            'latar_belakang'    => $validated['latar_belakang'],
            'tujuan_kegiatan'   => $validated['tujuan_kegiatan'],
            'sasaran_peserta'   => $validated['sasaran_peserta'],
            'jumlah_peserta'    => $validated['jumlah_peserta'],
            'narasumber'        => $validated['narasumber'],
            'pj_kegiatan'       => $validated['pj_kegiatan'],
            'instansi'          => $validated['instansi'],
            'alamat_instansi'   => $validated['alamat_instansi'],
            'wilayah'           => $validated['wilayah'],
            'no_hp_pj'          => $validated['no_hp_pj'],
            'fasilitas_tambahan'=> $validated['fasilitas_tambahan'] ?? [],
            'tgl_penggunaan'    => $validated['tgl_penggunaan'],
            'jam_mulai'         => $validated['jam_mulai'],
            'jam_berakhir'      => $validated['jam_berakhir'],
            'berkas_ktp'        => $ktpPath,
            'berkas_surat'      => $suratPath,
            'berkas_poster'     => $gambarPath,
            'status'            => 'pending',
        ]);

        return redirect()->route('home')->with('success', 'Permohonan peminjaman ruangan berhasil dikirim! Kami akan menghubungi Anda segera.');
    }
}
