name: Continuous Deployment

on:
  push:
    paths:
      - '**.php'
      - '**.blade.php' 
      - 'resources/**' 
      - 'public/**'
      - 'docker-compose.yml'
      - 'Dockerfile'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, sqlite, pdo_sqlite
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache  # Folder yang mau di-save/load
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP Dependencies
        run: |
          export COMPOSER_CACHE_DIR=/tmp/composer-cache
          composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHP Artisan Test
        run: |
          cp .env.testing .env
          php artisan key:generate
          php artisan test tests/Feature

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Build Assets (NPM)
        run: |
          npm install
          npm run build

      - name: Deploy to VPS via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!storage,!bootstrap/cache,!node_modules,!vendor,!.git,!.github,!.env,!.env.testing"
          target: "/home/${{ secrets.SSH_USER }}/EJSC"

      - name: Refresh Docker and Cache
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/EJSC
            # Pastikan jembatan storage ada
            docker compose exec -T app php artisan storage:link || true
            
            # Bersihkan cache
            docker compose exec -T app php artisan optimize:clear
            
            # Beri izin akses folder agar tidak 404/Forbidden
            sudo chmod -R 775 storage bootstrap/cache public
            sudo chown -R 1003:1003 storage bootstrap/cache public
            
            echo "Deployment Success, May the force be with you!"